### ISSUE TITLE
ERROR in ./src/main.js

### ISSUE THREAD

**Issue by hutxs** [ipselon/material-ui-prepack#2]
Module not found: Error: Cannot resolve 'file' or 'directory' ./routes/route
s.js in D:\Git\JSWork\material-ui-prepack\src
     @ ./src/main.js 25:22-51

**Comment by ipselon** [comment]
Sorry, missed some files. But, you can export project in structor, then build client ```npm run build-client```

**Comment by ipselon** [comment]
Fixed. Thanks!

**Comment by toddtarsi** [comment]
@ipselon - I believe this issue has returned with the bump to 0.6.0
