### ISSUE TITLE
Upgrade to material-ui@0.14.0

### ISSUE THREAD

**Issue by oliviertassinari** [ipselon/material-ui-prepack#3]
We have released a new version today with a lot of changes.

**Comment by ipselon** [comment]
Thank you. Will upgrade.

**Comment by ipselon** [comment]
material-ui lib was updated up to 0.14.1 version.

**Comment by oliviertassinari** [comment]
We release a hot fix with v0.14.2

**Comment by ipselon** [comment]
@oliviertassinari you are fast... :-) will update now, thanks.

**Comment by ipselon** [comment]
@oliviertassinari done.

**Comment by oliviertassinari** [comment]
@ipselon Awesome, thanks.
