### ISSUE TITLE
babel Cannot resolve modules  in babel-runtime

### ISSUE THREAD

**Issue by the-simian** [ipselon/material-ui-prepack#5]
> material-ui-sample@0.0.0 build C:\Work\struct-test-whatever
> webpack --config ./build-conf/webpack.config.js --progress --colors

Hash: 64448dcf0e2c0e55f3f0
Version: webpack 1.12.12
Child browser:
    Hash: 64448dcf0e2c0e55f3f0
    Version: webpack 1.12.12
    Time: 13965ms
         Asset     Size  Chunks             Chunk Names
     bundle.js   743 kB       0  [emitted]  main
    styles.css  1.08 MB       0  [emitted]  main
        + 501 hidden modules
    
    ERROR in ./src/middleware/promiseMiddleware.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/typeof' in C:\Work\struct-test-whatever\src\middleware
     @ ./src/middleware/promiseMiddleware.js 3:15-54
    
    ERROR in ./src/middleware/promiseMiddleware.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\middleware
     @ ./src/middleware/promiseMiddleware.js 7:16-56
    
    ERROR in ./src/routes/TabsPage.js
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/TabsPage.js 3:22-78
    
    ERROR in ./src/routes/TabsPage.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/TabsPage.js 7:23-70
    
    ERROR in ./src/routes/TabsPage.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/TabsPage.js 11:20-64
    
    ERROR in ./src/routes/TabsPage.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/TabsPage.js 15:34-92
    
    ERROR in ./src/routes/TabsPage.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/TabsPage.js 19:17-58
    
    ERROR in ./src/routes/PageProgress.js
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageProgress.js 3:22-78
    
    ERROR in ./src/routes/PageProgress.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageProgress.js 7:23-70
    
    ERROR in ./src/routes/PageProgress.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageProgress.js 11:20-64
    
    ERROR in ./src/routes/PageProgress.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageProgress.js 15:34-92
    
    ERROR in ./src/routes/PageProgress.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageProgress.js 19:17-58
    
    ERROR in ./src/middleware/promiseMiddleware.js
    Module not found: Error: Cannot resolve module 'lodash/utility/uniqueId' in C:\Work\struct-test-whatever\src\middleware
     @ ./src/middleware/promiseMiddleware.js 18:16-50
    
    ERROR in ./src/routes/PageSet2.js
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet2.js 3:22-78
    
    ERROR in ./src/routes/PageSet2.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet2.js 7:23-70
    
    ERROR in ./src/routes/PageSet2.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet2.js 11:20-64
    
    ERROR in ./src/routes/PageSet2.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet2.js 15:34-92
    
    ERROR in ./src/routes/PageSet2.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet2.js 19:17-58
    
    ERROR in ./src/routes/PageSet1.js
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet1.js 3:22-78
    
    ERROR in ./src/routes/PageSet1.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet1.js 7:23-70
    
    ERROR in ./src/routes/PageSet1.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet1.js 11:20-64
    
    ERROR in ./src/routes/PageSet1.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet1.js 15:34-92
    
    ERROR in ./src/routes/PageSet1.js
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\routes
     @ ./src/routes/PageSet1.js 19:17-58
    
    ERROR in ./src/components/DemoGroup/DemoAppBar.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\components\DemoGroup
     @ ./src/components/DemoGroup/DemoAppBar.jsx 3:16-56
    
    ERROR in ./src/components/DemoGroup/DemoAppBar.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\DemoGroup
     @ ./src/components/DemoGroup/DemoAppBar.jsx 7:22-78
    
    ERROR in ./src/components/DemoGroup/DemoAppBar.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\DemoGroup
     @ ./src/components/DemoGroup/DemoAppBar.jsx 11:23-70
    
    ERROR in ./src/components/DemoGroup/DemoAppBar.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\DemoGroup
     @ ./src/components/DemoGroup/DemoAppBar.jsx 15:20-64
    
    ERROR in ./src/components/DemoGroup/DemoAppBar.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\DemoGroup
     @ ./src/components/DemoGroup/DemoAppBar.jsx 19:34-92
    
    ERROR in ./src/components/DemoGroup/DemoAppBar.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\DemoGroup
     @ ./src/components/DemoGroup/DemoAppBar.jsx 23:17-58
    
    ERROR in ./src/components/FlexboxGrid/Box.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Box.jsx 3:16-56
    
    ERROR in ./src/components/FlexboxGrid/Box.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Box.jsx 7:22-78
    
    ERROR in ./src/components/FlexboxGrid/Box.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Box.jsx 11:23-70
    
    ERROR in ./src/components/FlexboxGrid/Box.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Box.jsx 15:20-64
    
    ERROR in ./src/components/FlexboxGrid/Box.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Box.jsx 19:34-92
    
    ERROR in ./src/components/FlexboxGrid/Box.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Box.jsx 23:17-58
    
    ERROR in ./src/components/FlexboxGrid/Row.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Row.jsx 3:16-56
    
    ERROR in ./src/components/FlexboxGrid/Row.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Row.jsx 7:22-78
    
    ERROR in ./src/components/FlexboxGrid/Row.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Row.jsx 11:23-70
    
    ERROR in ./src/components/FlexboxGrid/Row.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Row.jsx 15:20-64
    
    ERROR in ./src/components/FlexboxGrid/Row.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Row.jsx 19:34-92
    
    ERROR in ./src/components/FlexboxGrid/Row.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Row.jsx 23:17-58
    
    ERROR in ./src/components/FlexboxGrid/Col.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Col.jsx 3:16-56
    
    ERROR in ./src/components/FlexboxGrid/Col.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Col.jsx 7:22-78
    
    ERROR in ./src/components/FlexboxGrid/Col.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Col.jsx 11:23-70
    
    ERROR in ./src/components/FlexboxGrid/Col.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Col.jsx 15:20-64
    
    ERROR in ./src/components/FlexboxGrid/Col.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Col.jsx 19:34-92
    
    ERROR in ./src/components/FlexboxGrid/Col.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\FlexboxGrid
     @ ./src/components/FlexboxGrid/Col.jsx 23:17-58
    
    ERROR in ./src/components/MaterialUIEnhanced/IconMenuX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/IconMenuX.jsx 3:16-56
    
    ERROR in ./src/components/MaterialUIEnhanced/IconMenuX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/IconMenuX.jsx 7:22-78
    
    ERROR in ./src/components/MaterialUIEnhanced/IconMenuX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/IconMenuX.jsx 11:23-70
    
    ERROR in ./src/components/MaterialUIEnhanced/IconMenuX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/IconMenuX.jsx 15:20-64
    
    ERROR in ./src/components/MaterialUIEnhanced/IconMenuX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/IconMenuX.jsx 19:34-92
    
    ERROR in ./src/components/MaterialUIEnhanced/IconMenuX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/IconMenuX.jsx 23:17-58
    
    ERROR in ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx 3:16-56
    
    ERROR in ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx 7:22-78
    
    ERROR in ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx 11:23-70
    
    ERROR in ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx 15:20-64
    
    ERROR in ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx 19:34-92
    
    ERROR in ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/LeftNavIconButton.jsx 23:17-58
    
    ERROR in ./src/components/MaterialUITable/TableX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\MaterialUITable
     @ ./src/components/MaterialUITable/TableX.jsx 3:22-78
    
    ERROR in ./src/components/MaterialUITable/TableX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\MaterialUITable
     @ ./src/components/MaterialUITable/TableX.jsx 7:23-70
    
    ERROR in ./src/components/MaterialUITable/TableX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\MaterialUITable
     @ ./src/components/MaterialUITable/TableX.jsx 11:20-64
    
    ERROR in ./src/components/MaterialUITable/TableX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\MaterialUITable
     @ ./src/components/MaterialUITable/TableX.jsx 15:34-92
    
    ERROR in ./src/components/MaterialUITable/TableX.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\MaterialUITable
     @ ./src/components/MaterialUITable/TableX.jsx 19:17-58
    
    ERROR in ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx 3:22-78
    
    ERROR in ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx 7:23-70
    
    ERROR in ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx 11:20-64
    
    ERROR in ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx 15:34-92
    
    ERROR in ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\MaterialUIEnhanced
     @ ./src/components/MaterialUIEnhanced/SnackbarRaisedButton.jsx 19:17-58
    
    ERROR in ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in C:\Work\struct-test-whatever\src\components\MaterialUIDialogs
     @ ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx 3:16-56
    
    ERROR in ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in C:\Work\struct-test-whatever\src\components\MaterialUIDialogs
     @ ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx 7:22-78
    
    ERROR in ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in C:\Work\struct-test-whatever\src\components\MaterialUIDialogs
     @ ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx 11:23-70
    
    ERROR in ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in C:\Work\struct-test-whatever\src\components\MaterialUIDialogs
     @ ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx 15:20-64
    
    ERROR in ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in C:\Work\struct-test-whatever\src\components\MaterialUIDialogs
     @ ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx 19:34-92
    
    ERROR in ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx
    Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in C:\Work\struct-test-whatever\src\components\MaterialUIDialogs
     @ ./src/components/MaterialUIDialogs/FlatButtonDialog.jsx 23:17-58
    Child extract-text-webpack-plugin:
            + 2 hidden modules
    Child extract-text-webpack-plugin:
            + 8 hidden modules
    Child extract-text-webpack-plugin:
            + 2 hidden modules

**Comment by the-simian** [comment]
Hey I'm having a problem building right now when I run the `npm run build` and `npm run build-dev` commands. It would seem that babel cannot find any of its modules. If I then run the the application on the default `localhost:3000`, I get the error in the browser console.

```sh
Uncaught Error: Cannot find module "babel-runtime/core-js/object/get-prototype-of"
```

**Comment by ipselon** [comment]
@the-simian check if you have a `.babelrc` file in the project's root directory.

**Comment by ipselon** [comment]
as additional way try to download package from GH, then unpack and install dependencies manually.

**Comment by the-simian** [comment]
I have a babel-rc, please let me know if this is malformed:

``
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["transform-runtime", "add-module-exports"]
}
``

**Comment by the-simian** [comment]
references https://github.com/ipselon/structor/issues/43

**Comment by ipselon** [comment]
@the-simian yes, that is fine. Try to intall deps manually.

**Comment by the-simian** [comment]
I experienced the same result doing npm install myself, and also when I updated to the latest dependencies. the only exception was lodash, as your boilerplate seems to require lodasy@3.x.x

**Comment by the-simian** [comment]
I figured out the issue I am submitting a PR, pronto

**Comment by ipselon** [comment]
Thanks, will wait :-)

**Comment by the-simian** [comment]
resolved by https://github.com/ipselon/material-ui-prepack/pull/6

**Comment by the-simian** [comment]
I've got a PR, in that fixes the build errors. I was able to get it up and going in the structor editor, and also `npm run build && node server.js` runs, and the application is accessible on port 3000

**Comment by ipselon** [comment]
Thanks a lot for your contribution. 
1. Do you mean .structor dir or some other directory?
2. Yes, a Structor compatible project has to have a metadata folder `.structor`, this directory includes all needed files for Structor. 
3. Structor uses webpack for internal building throught webpack-dev-middleware. But you can use any kind of build system for the source code of your local project. So you don't have to use webpack in the source code, but some webpack's libs has to be there, for example loaders...

**Comment by the-simian** [comment]
1. I mean the public folder has an index.html, but after running build it adds a `/resources` folder with the built things in it. Since I added the .gitignore, that woudl make sense to ignore too - but I wanted to ask first.

2. ok thank you I'll study the structure of the .structor directory. Would you like some docs on how that works? I'd love to contribute as I learn how it works. If I do document it, and you want that, where should I submit? is the structor wiki being used, or maybe the readme file?

3. that makes sense, so you'd include it all in the package.json, but simply include other loaders in the dev-dependencies too.

**Comment by ipselon** [comment]
1. yes please. I'm really appreciate your help, I totally understand that this should be done by me, but there are so many things which I have to done before this...
2. I would love to have a docs, we lack of docs... please write some, and especially a tutorial.
3. exactly.

**Comment by ipselon** [comment]
I try to write some docs in Wiki pages of Structor, but I'm not native speaker :-) - this is really hard to me to write clean and understandable article.

**Comment by the-simian** [comment]
Hey after this, I will try to make time to do some docs. I understand your situation and I'd be happy to help. this is a good tool!

Tangentially related: [You might appreciate a video we had at our conference here in Oklahoma](https://www.youtube.com/watch?v=t4U7vr6KUVk). I've been wanting to make an effort to improve and help with documentation in projects that I think are good, since I enjoyed the talk.

**Comment by ipselon** [comment]
Well, now I'm busy with creating online generators, I want to make a system with pluggable generators for components which are connected to the REST backend (which desribed by metadata before the source code generation), or other full-fledged components. After all will be implemented, we can decide what should be done next, or what to fix, etc.

**Comment by ipselon** [comment]
BTW, thanks for video!

**Comment by the-simian** [comment]
Everything is updated, now as per our discussion! Thank you!

**Comment by ipselon** [comment]
@the-simian thanks a lot, I'll close this issue.
